export const surgeryOptions = [
  {label: '🚺 Cancer', value: 'cancer'},
  {label: '🦴 Orthopedic', value: 'ortho'},
  {label: '✨ Cosmetic', value: 'cosmetic'},
  {label: '🧠 Neurological', value: 'neuro'},
  {label: '👁️ Ophthalmology', value: 'ophtha'},
  {label: '🩺 General', value: 'surg'},
  {label: '👶 Pediatric', value: 'pediat'},
  {label: '🩸 Vascular', value: 'vascu'},
  {label: '🚹 Urology', value: 'urolo'},
  {label: '🚺 Gynecology', value: 'gynae'},
  {label: '❤️ Cardiac', value: 'cardi'},
];

export const specificSurgeries = {
  cardiac: [
    {label: '🫀 Coronary Artery Bypass', value: 'coronary_bypass'},
    {label: '💓 Valve Replacement', value: 'valve_replacement'},
    {label: '🫁 Heart Transplant', value: 'heart_transplant'},
    {label: '❤️‍🩹 Angioplasty', value: 'angioplasty'},
    {label: '🫀 Pacemaker Implantation', value: 'pacemaker'},
    {label: '💔 Aneurysm Repair', value: 'aneurysm_repair'},
    {label: '🫀 Cardiac Ablation', value: 'cardiac_ablation'},
    {label: '🫁 LVAD Implantation', value: 'lvad_implantation'},
    {label: '🫀 Heart Valve Repair', value: 'heart_valve_repair'},
    {label: '🩺 Cardiac Stent Placement', value: 'cardiac_stent'},
  ],
  orthopedic: [
    {label: '🦵 Knee Replacement', value: 'knee_replacement'},
    {label: '🦴 Hip Replacement', value: 'hip_replacement'},
    {label: '🦾 Shoulder Surgery', value: 'shoulder_surgery'},
    {label: '🦿 ACL Reconstruction', value: 'acl_reconstruction'},
    {label: '🦴 Spinal Fusion', value: 'spinal_fusion'},
    {label: '🦶 Ankle Reconstruction', value: 'ankle_reconstruction'},
    {label: '🦴 Fracture Repair', value: 'fracture_repair'},
    {label: '🖐️ Carpal Tunnel Release', value: 'carpal_tunnel'},
    {label: '🦾 Rotator Cuff Repair', value: 'rotator_cuff_repair'},
    {label: '🩺 Arthroscopy', value: 'arthroscopy'},
    {label: '🦿 Meniscus Repair', value: 'meniscus_repair'},
  ],
  cosmetic: [
    {label: '👃 Rhinoplasty', value: 'rhinoplasty'},
    {label: '👙 Breast Augmentation', value: 'breast_augmentation'},
    {label: '👁️ Blepharoplasty', value: 'blepharoplasty'},
    {label: '🤰 Tummy Tuck', value: 'tummy_tuck'},
    {label: '💇‍♀️ Hair Transplant', value: 'hair_transplant'},
    {label: '👄 Liposuction', value: 'liposuction'},
    {label: '🧖‍♀️ Facelift', value: 'facelift'},
    {label: '👂 Otoplasty', value: 'otoplasty'},
    {label: '💆‍♀️ Dermabrasion', value: 'dermabrasion'},
    {label: '🧔 Gynecomastia Surgery', value: 'gynecomastia_surgery'},
  ],
  neurological: [
    {label: '🧠 Brain Tumor Removal', value: 'brain_tumor_removal'},
    {label: '🌀 Deep Brain Stimulation', value: 'deep_brain_stimulation'},
    {label: '🦴 Spinal Fusion', value: 'spinal_fusion'},
    {label: '🧠 Epilepsy Surgery', value: 'epilepsy_surgery'},
    {label: '🩹 Craniotomy', value: 'craniotomy'},
    {label: '🧠 Hydrocephalus Shunt', value: 'hydrocephalus_shunt'},
    {label: '🦴 Microdiscectomy', value: 'microdiscectomy'},
    {label: '🧠 Peripheral Nerve Surgery', value: 'peripheral_nerve'},
    {label: '🧠 Gamma Knife Surgery', value: 'gamma_knife'},
    {label: '🧠 Pituitary Tumor Surgery', value: 'pituitary_tumor'},
  ],
  ophthalmology: [
    {label: '👁️ Cataract Surgery', value: 'cataract_surgery'},
    {label: '👓 LASIK', value: 'lasik'},
    {label: '🖼️ Retinal Detachment', value: 'retinal_detachment'},
    {label: '👁️ Glaucoma Surgery', value: 'glaucoma_surgery'},
    {label: '👁️ Corneal Transplant', value: 'corneal_transplant'},
    {label: '👁️ Vitrectomy', value: 'vitrectomy'},
    {label: '👁️ Strabismus Surgery', value: 'strabismus_surgery'},
    {label: '👁️ Ptosis Repair', value: 'ptosis_repair'},
    {label: '👁️ Orbital Surgery', value: 'orbital_surgery'},
  ],
  general: [
    {label: '🦠 Appendectomy', value: 'appendectomy'},
    {label: '🟡 Cholecystectomy', value: 'cholecystectomy'},
    {label: '🩹 Hernia Repair', value: 'hernia_repair'},
    {label: '🫁 Lobectomy', value: 'lobectomy'},
    {label: '🩺 Thyroidectomy', value: 'thyroidectomy'},
    {label: '🩹 Mastectomy', value: 'mastectomy'},
    {label: '🩹 Hysterectomy', value: 'hysterectomy'},
    {label: '🦷 Wisdom Teeth Removal', value: 'wisdom_teeth'},
    {label: '🩸 Hemorrhoidectomy', value: 'hemorrhoidectomy'},
    {label: '🩺 Splenectomy', value: 'splenectomy'},
    {label: '🩺 Colectomy', value: 'colectomy'},
  ],
  pediatric: [
    {label: '👶 Congenital Heart Surgery', value: 'congenital_heart'},
    {label: '👶 Cleft Lip/Palate Repair', value: 'cleft_repair'},
    {label: '👶 Pyloromyotomy', value: 'pyloromyotomy'},
    {label: '👶 Circumcision', value: 'circumcision'},
    {label: '👶 Orchidopexy', value: 'orchidopexy'},
    {label: '👶 Bladder Exstrophy Repair', value: 'bladder_exstrophy_repair'},
    {label: '👶 Esophageal Atresia Repair', value: 'esophageal_atresia'},
  ],
  vascular: [
    {label: '🩸 Varicose Vein Surgery', value: 'varicose_vein'},
    {label: '🩸 Carotid Endarterectomy', value: 'carotid_endarterectomy'},
    {label: '🩸 Aortic Aneurysm Repair', value: 'aortic_aneurysm'},
    {label: '🩸 Bypass Surgery', value: 'vascular_bypass'},
    {label: '🩸 Dialysis Access Surgery', value: 'dialysis_access'},
    {label: '🩸 Endovascular Repair', value: 'endovascular_repair'},
  ],
  urology: [
    {label: '🚹 Prostatectomy', value: 'prostatectomy'},
    {label: '🚺 Nephrectomy', value: 'nephrectomy'},
    {label: '🚹 Vasectomy', value: 'vasectomy'},
    {label: '🚹 Cystectomy', value: 'cystectomy'},
    {label: '🚹 Bladder Stone Removal', value: 'bladder_stone_removal'},
    {label: '🚹 Ureteral Stenting', value: 'ureteral_stenting'},
  ],
  gynecology: [
    {label: '🚺 Cesarean Section', value: 'c_section'},
    {label: '🚺 Myomectomy', value: 'myomectomy'},
    {label: '🚺 Oophorectomy', value: 'oophorectomy'},
    {label: '🚺 Tubal Ligation', value: 'tubal_ligation'},
    {label: '🚺 Endometrial Ablation', value: 'endometrial_ablation'},
    {label: '🚺 Hysteroscopy', value: 'hysteroscopy'},
  ],
};
